### ISSUE TITLE
Errors when trying to run

### ISSUE THREAD

**Issue by everte** [ChristianTovar/better-big-canvas#5]
I'd love to run and examine your project as inspiration on how to use liveview.

Sadly I can't get the example running on my computer (elixir 1.12 and erlang 24).

This is the console log:
`[warn] Ignoring unmatched topic "lv:phx-FoQ6rasukrUiVbGE" in Phoenix.LiveView.Socket
[warn] Ignoring unmatched topic "lv:phx-FoQ6rasukrUiVbGE" in Phoenix.LiveView.Socket
[warn] Ignoring unmatched topic "lv:phx-FoQ6rasukrUiVbGE" in Phoenix.LiveView.Socket
[error] GenServer #PID<0.2975.0> terminating
** (ArgumentError) argument error
    (better_big_canvas 0.1.0) lib/better_big_canvas/square.ex:20: BetterBigCanvas.Square.read/1
    (better_big_canvas 0.1.0) lib/better_big_canvas_web/live/board_live.ex:34: BetterBigCanvasWeb.BoardLive.get_pixels/1
    (better_big_canvas 0.1.0) lib/better_big_canvas_web/live/board_live.ex:29: BetterBigCanvasWeb.BoardLive.handle_event/3
    (phoenix_live_view 0.14.8) lib/phoenix_live_view/channel.ex:213: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 0.4.3) /home/evert/dev/elixir/better-big-canvas/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (phoenix_live_view 0.14.8) lib/phoenix_live_view/channel.ex:102: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "16847", payload: %{"event" => "canvas-ready", "type" => "hook", "value" => %{"id" => "1"}}, ref: "16848", topic: "lv:phx-FoQ6rasukrUiVbGE"}
State: %{components: {%{326 => {BetterBigCanvasWeb.BoardComponent, 326, %{flash: %{}, id: 326, myself: %Phoenix.LiveComponent.CID{cid: 326}, version: "bcc85704-e07d-4a37-a6c6-e232f623e2d5"}, %{}, {42726894523316783531833445939363244630, %{}}}, 33 => {BetterBigCanvasWeb.BoardComponent, 33, %{flash: %{}, id: 33, myself: %Phoenix.LiveComponent.CID{cid: 33}, version: "1be9dd88-6000-435b-9419-6651f385d566"}, %{}, {42726894523316783531833445939363244630, %{}}}, 289 => {BetterBigCanvasWeb.BoardComponent, 289, %{flash: %{}, id: 289, myself: %Phoenix.LiveComponent.CID{cid: 289}, version: "bd10593b-3c95-469f-a543-6014231f835b"}, %{}, {42726894523316783531833445939363244630, %{}}}, 168 => {BetterBigCanvasWeb.BoardComponent, 168, %{flash: %{}, id: 168, myself: %Phoenix.LiveComponent.CID{cid: 168}, version: "53509e8b-0511-48ca-b88a-9c9c4f4ecdc4"}, %{}, {42726894523316783531833445939363244630, %{}}}, 309 => {BetterBigCanvasWeb.BoardComponent, 309, %{flash: %{}, id: 309, myself: %Phoenix.LiveComponent.CID{cid: 309}, version: "ea28be6d-1cfa-4ab0-8f2f-548aef8d6980"}, %{}, {42726894523316783531833445939363244630, %{}}}, 117 => {BetterBigCanvasWeb.BoardComponent, 117, %{flash: %{}, id: 117, myself: %Phoenix.LiveComponent.CID{cid: 117}, version: "25af8a6e-b37d-43cc-9134-8011c4514fc6"}, %{}, {42726894523316783531833445939363244630, %{}}}, 377 => {BetterBigCanvasWeb.BoardComponent, 377, %{flash: %{}, id: 377, myself: %Phoenix.LiveComponent.CID{cid: 377}, version: "1a58e115-637a-4e53-a3d7-463e75562b98"}, %{}, {42726894523316783531833445939363244630, %{}}}, 277 => {BetterBigCanvasWeb.BoardComponent, 277, %{flash: %{}, id: 277, myself: %Phoenix.LiveComponent.CID{cid: 277}, version: "d24fe5c4-8a8b-43cf-becc-f72e3bd5cf59"}, %{}, {42726894523316783531833445939363244630, %{}}}, 399 => {BetterBigCanvasWeb.BoardComponent, 399, %{flash: %{}, id: 399, myself: %Phoenix.LiveComponent.CID{cid: 399}, version: "f85b739a-d9a8-47ac-91ff-a70abf549353"}, %{}, {42726894523316783531833445939363244630, %{}}}, 246 => {BetterBigCanvasWeb.BoardComponent, 246, %{flash: %{}, id: 246, myself: %Phoenix.LiveComponent.CID{cid: 246}, version: "829f4530-05d3-49d0-84ac-e92e5b857c85"}, %{}, {42726894523316783531833445939363244630, %{}}}, 175 => {BetterBigCanvasWeb.BoardComponent, 175, %{flash: %{}, id: 175, myself: %Phoenix.LiveComponent.CID{cid: 175}, version: "aff0824a-680e-4c8d-ad71-713efce08a52"}, %{}, {42726894523316783531833445939363244630, %{}}}, 219 => {BetterBigCanvasWeb.BoardComponent, 219, %{flash: %{}, id: 219, myself: %Phoenix.LiveComponent.CID{cid: 219}, version: "1d94ec55-06c0-494c-b5df-740f7f6d0cc1"}, %{}, {42726894523316783531833445939363244630, %{}}}, 360 => {BetterBigCanvasWeb.BoardComponent, 360, %{flash: %{}, id: 360, myself: %Phoenix.LiveComponent.CID{cid: 360}, version: "9fa1cb97-40ad-4ed8-a14a-d114e48f8931"}, %{}, {42726894523316783531833445939363244630, %{}}}, 12 => {BetterBigCanvasWeb.BoardComponent, 12, %{flash: %{}, id: 12, myself: %Phoenix.LiveComponent.CID{cid: 12}, version: "86bdb079-1ad8-4afc-ae9a-07d7a4d80d0d"}, %{}, {42726894523316783531833445939363244630, %{}}}, 192 => {BetterBigCanvasWeb.BoardComponent, 192, %{flash: %{}, id: 192, myself: %Phoenix.LiveComponent.CID{cid: 192}, version: "e480d944-9069-4927-ac3a-393c80fd720c"}, %{}, {42726894523316783531833445939363244630, %{}}}, 311 => {BetterBigCanvasWeb.BoardComponent, 311, %{flash: %{}, id: 311, myself: %Phoenix.LiveComponent.CID{cid: 311}, version: "aed3d961-2443-413c-abf3-a56552b29b29"}, %{}, {42726894523316783531833445939363244630, %{}}}, 327 => {BetterBigCanvasWeb.BoardComponent, 327, %{flash: %{}, id: 327, myself: %Phoenix.LiveComponent.CID{cid: 327}, version: "2a0abf64-e0da-434f-a02e-757c7c68f19d"}, %{}, {42726894523316783531833445939363244630, %{}}}, 188 => {BetterBigCanvasWeb.BoardComponent, 188, %{flash: %{}, id: 188, myself: %Phoenix.LiveComponent.CID{cid: 188}, version: "75e7f032-19ce-4acb-acca-2445efe6ca81"}, %{}, {42726894523316783531833445939363244630, %{}}}, 270 => {BetterBigCanvasWeb.BoardComponent, 270, %{flash: %{}, id: 270, myself: %Phoenix.LiveComponent.CID{cid: 270}, version: "13bf4014-38d7-46a5-bbc1-6f03db6e4eeb"}, %{}, {42726894523316783531833445939363244630, %{}}}, 157 => {BetterBigCanvasWeb.BoardComponent, 157, %{flash: %{}, id: 157, myself: %Phoenix.LiveComponent.CID{cid: 157}, version: "3c9b02be-fee4-4e70-9ab0-25068ee8f62b"}, %{}, {42726894523316783531833445939363244630, %{}}}, 349 => {BetterBigCanvasWeb.BoardComponent, 349, %{flash: %{}, id: 349, myself: %Phoenix.LiveComponent.CID{cid: 349}, version: "994ff4fd-ad09-4d72-9e06-f53534b6b9ef"}, %{}, {42726894523316783531833445939363244630, %{}}}, 132 => {BetterBigCanvasWeb.BoardComponent, 132, %{flash: %{}, id: 132, myself: %Phoenix.LiveComponent.CID{cid: 132}, version: "06473f84-a2d1-482b-a15f-a2adcd35fd9b"}, %{}, {42726894523316783531833445939363244630, %{}}}, 73 => {BetterBigCanvasWeb.BoardComponent, 73, %{flash: %{}, id: 73, myself: %Phoenix.LiveComponent.CID{cid: 73}, version: "1604e5aa-3015-4ba3-95e8-9c606ea87039"}, %{}, {42726894523316783531833445939363244630, %{}}}, 328 => {BetterBigCanvasWeb.BoardComponent, 328, %{flash: %{}, id: 328, myself: %Phoenix.LiveComponent.CID{cid: 328}, version: "36c0db0d-948f-43f4-bc6c-c6e9c7cdf6da"}, %{}, {42726894523316783531833445939363244630, %{}}}, 334 => {BetterBigCanvasWeb.BoardComponent, 334, %{flash: %{}, id: 334, myself: %Phoenix.LiveComponent.CID{cid: 334}, version: "05c7d258-abdd-4195-9280-385298fa5776"}, %{}, {42726894523316783531833445939363244630, %{}}}, 367 => {BetterBigCanvasWeb.BoardComponent, 367, %{flash: %{}, id: 367, myself: %Phoenix.LiveComponent.CID{cid: 367}, version: "35d0b2f8-c8e2-437d-840e-c70d1e497746"}, %{}, {42726894523316783531833445939363244630, %{}}}, 44 => {BetterBigCanvasWeb.BoardComponent, 44, %{flash: %{}, id: 44, myself: %Phoenix.LiveComponent.CID{cid: 44}, version: "3ae3fbdb-0758-44ab-8959-d3d1fe04b24d"}, %{}, {42726894523316783531833445939363244630, %{}}}, 183 => {BetterBigCanvasWeb.BoardComponent, 183, %{flash: %{}, id: 183, myself: %Phoenix.LiveComponent.CID{cid: 183}, version: "40994e6b-94ec-4a5f-8252-20e8ce85ba60"}, %{}, {42726894523316783531833445939363244630, %{}}}, 124 => {BetterBigCanvasWeb.BoardComponent, 124, %{flash: %{}, id: 124, myself: %Phoenix.LiveComponent.CID{cid: 124}, version: "afb63cf1-3825-44af-a1ee-a278bcbe34dd"}, %{}, {42726894523316783531833445939363244630, %{}}}, 239 => {BetterBigCanvasWeb.BoardComponent, 239, %{flash: %{}, id: 239, myself: %Phoenix.LiveComponent.CID{cid: 239}, version: "a3c9f602-4cca-433e-a1e7-9a0e11f8df3f"}, %{}, {42726894523316783531833445939363244630, %{}}}, 170 => {BetterBigCanvasWeb.BoardComponent, 170, %{flash: %{}, id: 170, myself: %Phoenix.LiveComponent.CID{cid: 170}, version: "ad8c6b49-15e5-41a2-8fa5-a7d77ebdcccf"}, %{}, {42726894523316783531833445939363244630, %{}}}, 23 => {BetterBigCanvasWeb.BoardComponent, 23, %{flash: %{}, id: 23, myself: %Phoenix.LiveComponent.CI (truncated)`

**Comment by ChristianTovar** [comment]
Fixed by visiting `localhost:4000/reset`
